sudo: false

language: emacs-lisp

env:
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis

before_install:
  - export PATH="/home/travis/.evm/bin:$PATH"
  - export PATH="/home/travis/.cask/bin:$PATH"
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - evm config path /tmp
  - evm install ${EVM_EMACS} --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python

install:
  - cask

script:
  - emacs --version
  - make test
